# Hegeman Lab UMN
# Mark Esler, 2018
#
# Calculate mean mass error of a mass spectrometry run
# by comparing observed and known masses of molecules.
#
# The input file must contain the columns:
# (1) molecule (2) formula (3) known_mass & (4) observed mass.

df <- read.table('input-data.tsv',header=T)

PROTON = 1.007276
for (i in 1:nrow(df)) {
  if (df$polarity[i] == "positive") {
    df$charged_mass[i] = df$monoisotopic_mass[i] + PROTON
  }
  if (df$polarity[i] == "negative") {
    df$charged_mass[i] = df$monoisotopic_mass[i] - PROTON
  }
}
df$delta <- df$charged_mass-df$observed_mass
df$mass_error <- df$delta/df$charged_mass*1e6
print(paste("Average PPM mass error:",mean(df$mass_error)))
print(paste("Overall SD per million:",sd(df$mass_error)))
write.table(df,file='output-data.tsv',sep="\t",row.names=F)

summary <- aggregate(cbind(observed_mass, mass_error) ~ charged_mass, df, mean)
summary$delta <- summary$charged_mass - summary$observed_mass
summary$molecule <- as.character(unique(df$molecule))
summary$formula <- as.character(unique(df$formula))
summary$monoisotopic_mass <- as.character(unique(df$monoisotopic_mass))
names(summary)[names(summary)=="observed_mass"] <- "observed_mass_avg"
names(summary)[names(summary)=="mass_error"] <- "mass_error_avg"
summary <- subset(summary, select=c(5,6,7,1,2,3,4))
write.table(summary,file='output-summary.tsv',sep="\t",row.names=F)

#install.packages("ggplot2",repos = "http://cran.us.r-project.org")
library(ggplot2)
p1 <- ggplot(df, aes(charged_mass, mass_error)) +
      geom_boxplot(aes(group = charged_mass)) +
      expand_limits(x=0,y=0) +
      labs(title="Mass error of data generated by Bruker AmazonSL",
	   subtitle="MS calibrated with vendor calibration mix\nMS using positive ionization and UltraScan mode\nSamples contained targeted low mass metabolites",
           x="Known mass (dalton)",
	   y="Observed mass error (PPM)")
#p2 <- ggplot(df, aes(charged_mass, delta)) + geom_boxplot(aes(group = known_mass)) + expand_limits(x=0,y=0)
ggsave("output-data.png")
